# Exercise

## Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,
1. Logistic Regression
2. SVM
3. Decision Tree
4. Random Forest

# 1. Import Libraries and Dataset

In [1]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [2]:
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

# 2. Machine Learning Models

In [4]:
models = [LogisticRegression(), SVC(), DecisionTreeClassifier(), RandomForestClassifier()]

# 3. Data Variables (X and y)

In [3]:
X = iris.data
y = iris.target

# 4. cross_val_score function

In [5]:
scores = []
for i in range(len(models)):
    scores.append(cross_val_score(models[i], X, y))

c:\users\hugo\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


## 4.1 Scores

In [6]:
scores

[array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ]),
 array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ]),
 array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ]),
 array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])]

## 4.2 Average Scores

In [7]:
average_score = []
for i in range(len(scores)):
    average_score.append(np.average(scores[i]))
average_score

[0.9733333333333334,
 0.9666666666666666,
 0.9533333333333334,
 0.9666666666666668]

## 4.3 Analysis

In [16]:
import pandas as pd
df = pd.DataFrame(data=[average_score], columns=models, index=['Score'])
df

LogisticRegression()     SVC()  DecisionTreeClassifier()  \
Score              0.973333  0.966667                  0.953333   

       RandomForestClassifier()  
Score                  0.966667

# Best score so far is from LogisticRegression: 0.973333